# Generated by Django 4.2.7 on 2026-03-11 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contentblock",
            name="type",
            field=models.CharField(
                choices=[
                    ("titre", "Titre"),
                    ("sous_titre", "Sous-titre"),
                    ("texte", "Texte"),
                    ("image", "Image"),
                    ("Description", "Description"),
                ],
                max_length=20,
            ),
        ),
    ]
