# Generated by Django 4.2.7 on 2026-03-11 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0002_alter_contentblock_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="projet",
            name="lien",
            field=models.URLField(blank=True, null=True),
        ),
    ]
