# Generated by Django 4.2.7 on 2026-03-11 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0003_projet_lien"),
    ]

    operations = [
        migrations.AddField(
            model_name="contentblock",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="contentblock",
            name="type",
            field=models.CharField(
                choices=[
                    ("titre", "Titre"),
                    ("sous_titre", "Sous-titre"),
                    ("texte", "Texte"),
                    ("image", "Image"),
                    ("description", "Description"),
                ],
                max_length=20,
            ),
        ),
    ]
