# Generated by Django 4.2.7 on 2026-03-11 09:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0004_contentblock_description_alter_contentblock_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contentblock",
            name="description",
        ),
        migrations.AddField(
            model_name="projet",
            name="date_creation",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="contentblock",
            name="type",
            field=models.CharField(
                choices=[
                    ("titre", "Titre"),
                    ("sous_titre", "Sous-titre"),
                    ("texte", "Texte"),
                    ("image", "Image"),
                ],
                max_length=20,
            ),
        ),
    ]
